using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using PiProxyGuard.Infrastructure.Options;

namespace PiProxyGuard.Infrastructure.Squid;

/// <summary>
/// Writes the aggregated blocklist as a Squid dstdomain ACL file and triggers
/// "squid -k reconfigure" when the content actually changed. To keep the proxy
/// resilient, a ".bak" copy of the previous ACL is taken before each rewrite;
/// if the reload command fails the previous file is restored automatically so a
/// malformed blocklist can never take the proxy down.
/// </summary>
public class SquidAclWriter
{
    private readonly BlocklistOptions _options;
    private readonly ILogger<SquidAclWriter> _logger;

    public SquidAclWriter(IOptions<BlocklistOptions> options, ILogger<SquidAclWriter> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    /// <summary>
    /// Returns true when the file was rewritten (and the reload command executed).
    /// On a failed reload the previous ACL is restored and the method still
    /// returns true (a change was attempted), but <see cref="LastReloadSucceeded"/>
    /// reflects whether the new content is actually live.
    /// </summary>
    public async Task<bool> WriteIfChangedAsync(IReadOnlyList<string> domains, CancellationToken cancellationToken)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by PiProxyGuard — do not edit by hand.");
        foreach (var domain in domains)
        {
            // Leading dot blocks the domain and all of its subdomains.
            builder.Append('.').AppendLine(domain);
        }

        var newContent = builder.ToString();
        var path = _options.AclFilePath;
        var fileExisted = File.Exists(path);

        if (fileExisted)
        {
            var existing = await File.ReadAllTextAsync(path, cancellationToken);
            if (HashOf(existing) == HashOf(newContent))
            {
                return false;
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);

        // Keep a backup of the currently-live ACL so we can roll back on failure.
        string? backupPath = null;
        if (_options.BackupAclBeforeWrite && fileExisted)
        {
            backupPath = path + ".bak";
            File.Copy(path, backupPath, overwrite: true);
        }

        // Write atomically: temp file + rename, so Squid never reads a half-written ACL.
        var tempPath = path + ".tmp";
        await File.WriteAllTextAsync(tempPath, newContent, cancellationToken);
        File.Move(tempPath, path, overwrite: true);

        _logger.LogInformation("ACL file {Path} rewritten with {Count} domains", path, domains.Count);

        LastReloadSucceeded = await RunReloadCommandAsync(cancellationToken);

        if (!LastReloadSucceeded && backupPath is not null && File.Exists(backupPath))
        {
            // Reload failed — restore the previous ACL so the proxy keeps serving.
            File.Copy(backupPath, path, overwrite: true);
            _logger.LogWarning("Reload failed; rolled back ACL file {Path} to the previous version", path);
            await RunReloadCommandAsync(cancellationToken);
        }

        return true;
    }

    /// <summary>Whether the last reload command succeeded (true when no command configured).</summary>
    public bool LastReloadSucceeded { get; private set; } = true;

    /// <summary>
    /// Runs the configured reload command. Returns true on success (or when no
    /// command is configured). Overridable so tests can simulate reload failure.
    /// </summary>
    protected virtual async Task<bool> RunReloadCommandAsync(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(_options.ReloadCommand))
        {
            return true;
        }

        try
        {
            var startInfo = new ProcessStartInfo("/bin/sh", $"-c \"{_options.ReloadCommand}\"")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };

            using var process = Process.Start(startInfo);
            if (process is null)
            {
                _logger.LogWarning("Reload command could not be started");
                return false;
            }

            await process.WaitForExitAsync(cancellationToken);

            if (process.ExitCode == 0)
            {
                _logger.LogInformation("Proxy reloaded via '{Command}'", _options.ReloadCommand);
                return true;
            }

            var stderr = await process.StandardError.ReadToEndAsync(cancellationToken);
            _logger.LogWarning("Reload command exited with {Code}: {Error}", process.ExitCode, stderr.Trim());
            return false;
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogWarning(ex, "Failed to run reload command '{Command}'", _options.ReloadCommand);
            return false;
        }
    }

    private static string HashOf(string content) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
}
