using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using PiProxyGuard.Infrastructure.Options;

namespace PiProxyGuard.Infrastructure.Squid;

/// <summary>
/// Writes the aggregated blocklist as a Squid dstdomain ACL file and
/// triggers "squid -k reconfigure" when the content actually changed.
/// </summary>
public class SquidAclWriter
{
    private readonly BlocklistOptions _options;
    private readonly ILogger<SquidAclWriter> _logger;

    public SquidAclWriter(IOptions<BlocklistOptions> options, ILogger<SquidAclWriter> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    /// <summary>
    /// Returns true when the file was rewritten (and the reload command executed).
    /// </summary>
    public async Task<bool> WriteIfChangedAsync(IReadOnlyList<string> domains, CancellationToken cancellationToken)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by PiProxyGuard — do not edit by hand.");
        foreach (var domain in domains)
        {
            // Leading dot blocks the domain and all of its subdomains.
            builder.Append('.').AppendLine(domain);
        }

        var newContent = builder.ToString();
        var path = _options.AclFilePath;

        if (File.Exists(path))
        {
            var existing = await File.ReadAllTextAsync(path, cancellationToken);
            if (HashOf(existing) == HashOf(newContent))
            {
                return false;
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);

        // Write atomically: temp file + rename, so Squid never reads a half-written ACL.
        var tempPath = path + ".tmp";
        await File.WriteAllTextAsync(tempPath, newContent, cancellationToken);
        File.Move(tempPath, path, overwrite: true);

        _logger.LogInformation("ACL file {Path} rewritten with {Count} domains", path, domains.Count);

        await RunReloadCommandAsync(cancellationToken);
        return true;
    }

    private async Task RunReloadCommandAsync(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(_options.ReloadCommand))
        {
            return;
        }

        try
        {
            var startInfo = new ProcessStartInfo("/bin/sh", $"-c \"{_options.ReloadCommand}\"")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };

            using var process = Process.Start(startInfo);
            if (process is null)
            {
                _logger.LogWarning("Reload command could not be started");
                return;
            }

            await process.WaitForExitAsync(cancellationToken);

            if (process.ExitCode == 0)
            {
                _logger.LogInformation("Proxy reloaded via '{Command}'", _options.ReloadCommand);
            }
            else
            {
                var stderr = await process.StandardError.ReadToEndAsync(cancellationToken);
                _logger.LogWarning("Reload command exited with {Code}: {Error}", process.ExitCode, stderr.Trim());
            }
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogWarning(ex, "Failed to run reload command '{Command}'", _options.ReloadCommand);
        }
    }

    private static string HashOf(string content) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
}
