using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using PiProxyGuard.Infrastructure.Options;

namespace PiProxyGuard.Infrastructure.Squid;

/// <summary>
/// Writes the upstream-tunnel domain list as a Squid dstdomain ACL file
/// (tunnel_domains.acl) and triggers "squid -k reconfigure" when the content
/// actually changes. Mirrors <see cref="SquidAclWriter"/>: the file is rewritten
/// in place (the service user owns the ACL file but usually not its parent
/// directory), and the previous content is held in memory and restored if the
/// reload command fails, so a malformed list can never wedge the proxy.
/// </summary>
public class TunnelAclWriter
{
    private readonly TunnelOptions _options;
    private readonly ILogger<TunnelAclWriter> _logger;

    public TunnelAclWriter(IOptions<TunnelOptions> options, ILogger<TunnelAclWriter> logger)
    {
        _options = options.Value;
        _logger = logger;
    }

    /// <summary>
    /// Guarantees the ACL file exists so Squid can always read it, even before
    /// any domain has been tunneled. squid.conf references this file once the
    /// upstream block is enabled, so a missing file produces a "Can not open
    /// file" warning. Writing a header-only placeholder (no domains = nothing
    /// tunneled) keeps the proxy healthy. No-op when the file already exists.
    /// </summary>
    public async Task EnsureAclFileExistsAsync(CancellationToken cancellationToken = default)
    {
        var path = _options.AclFilePath;
        if (File.Exists(path))
        {
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        await File.WriteAllTextAsync(
            path,
            "# Generated by PiProxyGuard - placeholder until the first upstream-tunnel update." + Environment.NewLine,
            cancellationToken);
        _logger.LogInformation("Seeded empty upstream-tunnel ACL file {Path} (no domains yet)", path);
    }

    /// <summary>
    /// Returns true when the file was rewritten (and the reload command executed).
    /// On a failed reload the previous ACL is restored and the method still
    /// returns true, but <see cref="LastReloadSucceeded"/> reflects whether the
    /// new content is actually live.
    /// </summary>
    public async Task<bool> WriteIfChangedAsync(IReadOnlyList<string> domains, CancellationToken cancellationToken)
    {
        // Squid's dstdomain ACL treats a ".parent" entry as already covering every
        // subdomain and FATALs if a redundant child is also present. Collapse
        // children whose parent is tunneled before writing the file (reuse the
        // blocklist writer's proven logic).
        var effectiveDomains = SquidAclWriter.CollapseToBroadestDomains(domains);

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by PiProxyGuard - do not edit by hand.");
        foreach (var domain in effectiveDomains)
        {
            // Leading dot tunnels the domain and all of its subdomains.
            builder.Append('.').AppendLine(domain);
        }

        var newContent = builder.ToString();
        var path = _options.AclFilePath;
        var fileExisted = File.Exists(path);

        string? previousContent = null;
        if (fileExisted)
        {
            previousContent = await File.ReadAllTextAsync(path, cancellationToken);
            if (HashOf(previousContent) == HashOf(newContent))
            {
                return false;
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        await File.WriteAllTextAsync(path, newContent, cancellationToken);

        _logger.LogInformation(
            "Upstream-tunnel ACL file {Path} rewritten with {Count} domains", path, effectiveDomains.Count);

        LastReloadSucceeded = await RunReloadCommandAsync(cancellationToken);

        if (!LastReloadSucceeded && previousContent is not null)
        {
            await File.WriteAllTextAsync(path, previousContent, cancellationToken);
            _logger.LogWarning("Reload failed; rolled back upstream-tunnel ACL file {Path}", path);
            await RunReloadCommandAsync(cancellationToken);
        }

        return true;
    }

    /// <summary>Whether the last reload command succeeded (true when no command configured).</summary>
    public bool LastReloadSucceeded { get; private set; } = true;

    /// <summary>
    /// Runs the configured reload command. Returns true on success (or when no
    /// command is configured). Overridable so tests can simulate reload failure.
    /// </summary>
    protected virtual async Task<bool> RunReloadCommandAsync(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(_options.ReloadCommand))
        {
            return true;
        }

        try
        {
            var startInfo = new ProcessStartInfo("/bin/sh", $"-c \"{_options.ReloadCommand}\"")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };

            using var process = Process.Start(startInfo);
            if (process is null)
            {
                _logger.LogWarning("Reload command could not be started");
                return false;
            }

            await process.WaitForExitAsync(cancellationToken);

            if (process.ExitCode == 0)
            {
                _logger.LogInformation("Proxy reloaded via '{Command}'", _options.ReloadCommand);
                return true;
            }

            var stderr = await process.StandardError.ReadToEndAsync(cancellationToken);
            _logger.LogWarning("Reload command exited with {Code}: {Error}", process.ExitCode, stderr.Trim());
            return false;
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            _logger.LogWarning(ex, "Failed to run reload command '{Command}'", _options.ReloadCommand);
            return false;
        }
    }

    private static string HashOf(string content) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content)));
}
