#!/usr/bin/env bash
# PiProxyGuard - upstream tunnel for selected domains.
#
# Wires the *Pi side* of the upstream tunnel into squid.conf: a cache_peer
# (parent proxy) plus cache_peer_access / never_direct rules that force ONLY the
# domains listed in /etc/squid/tunnel_domains.acl to go out through that parent,
# while everything else keeps going direct. The domain list itself is managed at
# runtime from the PiProxyGuard dashboard (Upstream tunnel page) or REST API -
# this script only configures the parent proxy once. Idempotent and reversible.
#
#   sudo ./setup-upstream.sh enable <host> <port> [name]   # route listed domains via host:port
#   sudo ./setup-upstream.sh disable                       # remove everything we added
#   sudo ./setup-upstream.sh status                        # show current state
#
# Example: tunnel the dashboard-listed domains through a VPN-side proxy:
#   sudo ./setup-upstream.sh enable 10.8.0.1 8888
#
# NOTE: with never_direct, a tunneled domain has NO direct fallback - if the
# parent proxy is down those domains stop working until you 'disable' or fix it.
set -euo pipefail

SQUID_CONF=/etc/squid/squid.conf
ACL=/etc/squid/tunnel_domains.acl
TAG=piproxyguard-upstream-tunnel
BEGIN="# >>> ${TAG} >>>"
END="# <<< ${TAG} <<<"
PEER_NAME_DEFAULT=ppg_upstream

log()  { echo ">> $*"; }
warn() { echo "!! $*" >&2; }

need_root() { [ "$(id -u)" -eq 0 ] || { warn "run as root (sudo)"; exit 1; }; }

ensure_acl() {
  if [ ! -f "$ACL" ]; then
    log "creating empty $ACL (PiProxyGuard fills it from the dashboard)"
    echo "# Generated by PiProxyGuard - upstream tunnel domains." > "$ACL"
    chown proxy:proxy "$ACL" 2>/dev/null || true
  fi
}

remove_block() {
  [ -f "$SQUID_CONF" ] || return 0
  if grep -qF "$BEGIN" "$SQUID_CONF"; then
    sed -i "/$(printf '%s' "$BEGIN" | sed 's/[][\.*^$/]/\\&/g')/,/$(printf '%s' "$END" | sed 's/[][\.*^$/]/\\&/g')/d" "$SQUID_CONF"
  fi
}

add_block() {
  local host="$1" port="$2" name="$3"
  cp -a "$SQUID_CONF" "${SQUID_CONF}.bak.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  remove_block
  # drop trailing blank lines so repeated enable/disable can't pile them up
  sed -i -e :a -e '/^[[:space:]]*$/{$d;N;ba;}' "$SQUID_CONF" 2>/dev/null || true
  {
    echo ""
    echo "$BEGIN"
    echo "# Upstream tunnel. Managed by setup-upstream.sh; edits here are overwritten."
    echo "# Domain list is maintained by PiProxyGuard (dashboard / REST)."
    echo "cache_peer ${host} parent ${port} 0 no-query default name=${name}"
    echo "acl piproxyguard_tunnel dstdomain \"${ACL}\""
    echo "cache_peer_access ${name} allow piproxyguard_tunnel"
    echo "cache_peer_access ${name} deny all"
    echo "never_direct allow piproxyguard_tunnel"
    echo "$END"
  } >> "$SQUID_CONF"
}

reload_squid() {
  if squid -k parse >/dev/null 2>&1; then
    squid -k reconfigure 2>/dev/null || systemctl reload squid 2>/dev/null || systemctl restart squid 2>/dev/null || true
  else
    warn "squid -k parse failed - NOT reloading. Check $SQUID_CONF"
    return 1
  fi
}

cmd_enable() {
  need_root
  local host="${1:-}" port="${2:-}" name="${3:-$PEER_NAME_DEFAULT}"
  if [ -z "$host" ] || [ -z "$port" ]; then
    warn "usage: $0 enable <host> <port> [name]"; exit 2
  fi
  log "enabling upstream tunnel via ${host}:${port} (peer '${name}')"
  ensure_acl
  add_block "$host" "$port" "$name"
  reload_squid || { warn "squid did not reload; check the config"; return 1; }
  log "DONE. Domains listed on the dashboard's 'Upstream tunnel' page now route via ${host}:${port}."
  echo ""
  echo "   Add domains in the PiProxyGuard dashboard -> Upstream tunnel (or POST /api/tunnel)."
  echo "   Test from a proxied client:"
  echo "     curl.exe -x http://<pi>:3128 -I https://example.com"
  echo "   (a tunneled domain will be served through ${host}:${port}, not directly)"
}

cmd_disable() {
  need_root
  log "disabling upstream tunnel"
  remove_block
  reload_squid || true
  log "DONE. Tunnel removed - all domains go direct again. (tunnel_domains.acl is kept.)"
}

cmd_status() {
  echo "squid block      : $(grep -qF "$BEGIN" "$SQUID_CONF" 2>/dev/null && echo present || echo absent)"
  if grep -qF "$BEGIN" "$SQUID_CONF" 2>/dev/null; then
    echo "cache_peer       :"; grep -A0 '^cache_peer ' "$SQUID_CONF" 2>/dev/null | sed 's/^/   /' || true
  fi
  if [ -f "$ACL" ]; then
    echo "tunneled domains : $(grep -c '^\.' "$ACL" 2>/dev/null || echo 0) in $ACL"
  else
    echo "tunneled domains : (acl file absent)"
  fi
}

case "${1:-}" in
  enable)  shift; cmd_enable "$@" ;;
  disable) cmd_disable ;;
  status)  cmd_status ;;
  *) echo "usage: $0 {enable <host> <port> [name]|disable|status}"; exit 2 ;;
esac
